name: phasst phase
version: "1.0"
author: Haynes Heaton <whheaton@gmail.com>
about: phasing
args:
    - output:
        long: output
        short: o
        takes_value: true
        required: true
        help: output directory
    - het_kmers:
        long: het_kmers
        short: k
        takes_value: true
        required: true
        help: het_kmers.tsv from het_snp_kmers output
    - contig_kmer_depths:
        long: contig_kmer_depths
        takes_value: true
        required: true
        help: tsv file with contig_name\tdepth 
    - sex_contig_depth_cutoff:
        long: sex_contig_depth_cutoff
        takes_value: true
        required: false
        help: kmer coverage multiple cutoff to be called a sex contig, default = 0.65 ( * avg_depth )
    - sex_contig_het_kmer_density_cutoff:
        long: sex_contig_het_kmer_density_cutoff
        takes_value: true
        required: false
        help: het kmer density cutoff for contig to be called a sex contig, default = 0.1 ( * avg het kmer density )
    - linked_read_mols:
        long: linked_read_mols
        short: l
        takes_value: true
        required: false
        help: linked read molecule kmers from output of molecule_kmers in fofn (file of filenames) format
    - hic_mols:
        long: hic_mols
        short: h
        required: true
        takes_value: true
        help: hic kmers as output from molecule_kmers in fofn format
    - long_read_mols:
        long: long_read_mols
        required: false
        takes_value: true
        help: long reads as output from molecule_kmers in fofn format
    - threads:
        short: t
        long: threads
        required: false
        takes_value: true
        help: max number of threads.
    - seed:
        short: s
        long: seed
        required: false
        takes_value: true
        help: random seed
    - restarts:
        long: restarts
        required: false
        takes_value: true
        help: number of random restarts
    - assembly_fasta:
        short: f
        long: assembly_fasta
        required: true
        help: assembly fasta file
        takes_value: true
    - assembly_kmers:
        short: a
        long: assembly_kmers
        required: true
        help: assembly kmers file from molecule_kmers
        takes_value: true
    - ploidy:
        short: p
        long: ploidy
        required: false
        help: ploidy of organism, default 2
        takes_value: true
    - min_hic_links:
        long: min_hic_links
        required: false
        help: minimum number of hic links to count in same phase block (default 4)
        takes_value: true
    - min_minor_allele_fraction:
        long: min_minor_allele_fraction
        required: false
        takes_value: true
        help: minimum minor allele fraction to be counted for phasing consistency -- if low it might not be actually heterozygous (default 0.15)
    - min_phasing_consistency_counts:
        long: min_phasing_consistency_counts
        required: false
        takes_value: true
        help: min number of molecules reaching forward to new kmer that are phasing consistent (default 8)
    - min_phasing_consistency_percent:
        long: min_phasing_consistency_percent
        help: min percent of molecules reaching forward to new kmer that are phasing consistent (default 0.9)
        required: false
        takes_value: true
    - break_window:
        long: break_window
        required: false
        help: window of snps used to determine if contig should be split (default 100)
        takes_value: true
        